from enum import Enum


class DatabaseType(str, Enum):
    POSTGRESQL = "POSTGRESQL"
    MYSQL = "MYSQL"
    SQL_SERVER = "SQL_SERVER"
    ORACLE = "ORACLE"


class DiscoveryScope(str, Enum):
    COLUMN_CLASSIFICATION = "COLUMN_CLASSIFICATION"
    DEPENDENCY_MAP = "DEPENDENCY_MAP"
    REGULATORY_COMPLIANCE = "REGULATORY_COMPLIANCE"
    HIPAA_COMPLIANCE = "HIPAA_COMPLIANCE"


class RunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StageStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class DisplayClassification(str, Enum):
    PUBLIC = "PUBLIC"
    PII = "PII"
    PHI = "PHI"
    FINANCIAL = "FINANCIAL"
    SENSITIVE = "SENSITIVE"


class HipaaSeverity(str, Enum):
    GOOD = "GOOD"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SERIOUS = "SERIOUS"
    CRITICAL = "CRITICAL"


class FrameworkImplementationStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    PLANNED = "PLANNED"
    DISABLED = "DISABLED"


class PolicyPackStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class ComplianceAssessmentStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    PARTIAL = "PARTIAL"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_ASSESSED = "NOT_ASSESSED"


class EvidenceVerificationStatus(str, Enum):
    CONFIRMED = "CONFIRMED"
    NOT_CONFIRMED = "NOT_CONFIRMED"
    NOT_SURE = "NOT_SURE"
